.gitignore, scripts/add_vata_to_bd.tcl, scripts/setup_trenz_breakout.tcl, src/hdl/vata460p3_driver.vhd
Currently only sets/gets config, which is stored in BRAM.
I have been working with an emulator, which will be added in a new
branch in a bit. The emulator branch will remain apart from master.
=> Adding vata460.3 driver that sets/gets configuration register

Makefile, scripts/env.bat
Also uses the setup.done file to see if setup should be re-run.
=> changes to allow for making on windows

Makefile, scripts/bit_pre.tcl, scripts/compile.tcl, scripts/connect_gpio_to_vata_ports.tcl, scripts/export_hardware.tcl, scripts/setup_trenz_breakout.tcl, src/c/toggle_gpio.c
Are we cool to merge this in or is there more make stuff that should be done?
=> Add make stuff

src/hdl/vata_460p3_axi_interface_fsm.vhd, src/hdl/vata_460p3_axi_interface_v2_0.vhd
The vata_460p3_axi_interface_v2_0.vhd is an example of how this
could be used in an axi peripheral.
=> Adding vata interface fsm

src/hdl/tb/set_cfg_fsm_tb.vhd, src/hdl/tb/set_get_cfg_fsm_tb.vhd, src/hdl/tb/vata_fsm_daq_tb.vhd, src/hdl/tb/vata_fsm_daq_v2_tb.vhd, src/hdl/vata_460p3_axi_interface_v2_0.vhd, src/hdl/vata_460p3_iface_fsm.vhd
Also fixing TB's. This branch should have been named for the
trigger_out, but I forgot that it was added (and setted off the tb
updates).
=> Adding `trigger_out` to fsm

gse/src/vata460_config_register.csv, gse/src/vata460_config_register.py
Merging config file script into Master.
=> Config register python

gse/src/vata460_config_register.py
* byte-flips:
In order to actually write out in the order we want, it appears
that we have to reorder each byte of the configuration register.
* register-flips:
And each register is little-endian within its bitrange, so more
bit reordering. This can be turned off with the `little_endian`
kwarg, but it seems to work, so why do that? We also haven't verified
that every register abides this ordering. Currently assuming all do.
=> A bunch of bit reordering

src/petalinux/apps/README.md, src/petalinux/apps/silayer-server/Makefile, src/petalinux/apps/silayer-server/data_emitter.cpp, src/petalinux/apps/silayer-server/data_emitter.hpp, src/petalinux/apps/silayer-server/silayer_server.cpp, src/petalinux/apps/silayer-server/silayer_server.hpp, src/petalinux/apps/silayer-server/test_server.py, src/petalinux/apps/silayer-server/vtctrl_client.cpp, src/petalinux/apps/silayer-server/vtctrl_server.cpp, src/petalinux/si-layer/build-and-scp, src/petalinux/si-layer/just-scp, src/petalinux/si-layer/project-spec/meta-user/recipes-apps/vatactrl/files/vatactrl/configure.ac, src/petalinux/si-layer/project-spec/meta-user/recipes-apps/vatactrl/files/vatactrl/include/vata_constants.hpp, src/petalinux/si-layer/project-spec/meta-user/recipes-apps/vatactrl/files/vatactrl/include/vata_ctrl.hpp, src/petalinux/si-layer/project-spec/meta-user/recipes-apps/vatactrl/files/vatactrl/src/Makefile.am, src/petalinux/si-layer/project-spec/meta-user/recipes-apps/vatactrl/files/vatactrl/src/vata_ctrl.cpp
Also modified vatactrl petalinux app to create library
that can be linked against when building on the silayer board
=> Started coding up the silicon layer server

src/sdk-apps/calctrl/README.txt, src/sdk-apps/calctrl/cal_ctrl.cpp, src/sdk-apps/calctrl/cal_ctrl.hpp, src/sdk-apps/calctrl/calctrl.cpp
I am super stuck on why the petalinux-build calctrl, with the exact
same code, does not work most of the time.
I have even swapped the addresses around, so it's not an addressing
thing.
Anyways, this will at least work in case the calibrator is needed
before the problem is fixed.
=> Adding sdk directory for calctrl program

src/py/silayer/README.md, src/py/silayer/python/__init__.py, src/py/silayer/python/cfg_reg.py, src/py/silayer/python/client.py, src/py/silayer/python/data_recvr.py, src/py/silayer/setup.py
This includes the ability to start data streaming into
a local file.
The "API" is the `silayer.client.Client` class
=> Adding code to interact with silayer server

src/py/silayer/python/raw2hdf.py
This is a cheap and dumb way to get data packets.
Hopefully a cool and smart way will exist soon
=> Added raw2hdf.lame_byte_iterator

cores/vata_460p3/component.xml, cores/vata_460p3/src/event_id_s2p.vhd, cores/vata_460p3/src/stay_high_n_cycles.vhd, cores/vata_460p3/src/vata_460p3_axi_interface_v3_0.vhd, cores/vata_460p3/src/vata_460p3_iface_fsm.vhd
Still not acknowledging trigger-acknowledge at this point.
=> Committing updates that got trigger module working with the vata

scripts/setup_project.tcl, src/block_diagrams/dbe_production/dbe_production_bd.tcl, src/hdl/fake_asic.vhd, src/hdl/fake_asic_gen_hit.vhd, src/py/silayer/setup.py, src/py/silayer/src/raw2hdf.c
This commit contains the set of minor changes that occured
at GSFC, but haven't made it in the other commits yet.
Also the block-diagram building script now builds the
two asic design. That's probably the headliner on this commit
=> Committing random minor changes and 2 asic design

src/petalinux/users/README.md, src/petalinux/users/lucas/profile.d/README.md, src/petalinux/users/lucas/profile.d/calctrl-completion.sh, src/petalinux/users/lucas/profile.d/lucas-settings.sh, src/petalinux/users/lucas/profile.d/vatactrl-completion.sh
Also some bash completion stuff for `vatactrl` and `calctrl`
=> Adding petalinux users directory

src/petalinux/apps/silayer-server/data_packet.cpp
Hopefully this fixes the malloc issue.
=> Found issues in data-packet size accounting

src/petalinux/users/lucas/etc/init.d/ntp
Instructions for setting up automatic ntp on startup:
https://github.com/ComPair/ComPair-tracker-FPGA/wiki/Building-ntp-on-the-zynq#9-setting-up-the-init-script
=> Adding ntp init script

cores/vata_460p3/component.xml, cores/vata_460p3/src/rising_edge_vector.vhd, cores/vata_460p3/src/vata_460p3_axi_interface_v3_0.vhd, cores/vata_460p3/src/vata_460p3_axi_interface_v3_0_S00_AXI.vhd, cores/vata_460p3/src/vata_460p3_iface_fsm.vhd, src/block_diagrams/breakout/breakout_bd.tcl, src/block_diagrams/dbe_production/dbe_production_bd.tcl, src/petalinux/apps/silayer-ctrl/src/vatactrl.cpp, src/petalinux/apps/silayer-lib/include/vata_constants.hpp, src/petalinux/apps/silayer-lib/include/vata_ctrl.hpp, src/petalinux/apps/silayer-lib/src/vata_ctrl.cpp, src/petalinux/apps/silayer-server/data_emitter.cpp, src/petalinux/apps/silayer-server/silayer_server.cpp, src/petalinux/apps/silayer-server/silayer_server.hpp, src/petalinux/users/lucas/profile.d/vatactrl-completion.sh, src/py/silayer/python/client.py, src/py/silayer/python/raw2hdf.py
This has quite a bit of updates
* Now local asic triggers are done off rising edge of o5
* New trigger enable/disable functions in software
* Forced-triggers can be disabled for an ASIC now
* New "clear fifo" command
* Slew of other things. This is not a helpful bullet point.
=> Rising edge o5 trigger

cores/vata_460p3/src/vata_460p3_axi_interface_v3_0.vhd, cores/vata_460p3/src/vata_460p3_iface_fsm.vhd, src/petalinux/apps/silayer-ctrl/src/vatactrl.cpp, src/petalinux/apps/silayer-lib/include/vata_constants.hpp, src/petalinux/apps/silayer-lib/include/vata_ctrl.hpp, src/petalinux/apps/silayer-lib/src/dac_ctrl.cpp, src/petalinux/apps/silayer-lib/src/vata_ctrl.cpp, src/petalinux/apps/silayer-server/silayer_server.cpp, src/petalinux/apps/silayer-server/silayer_server.hpp, src/py/silayer/python/client.py
Force the VATA fsm into idle state.
Code builds, but needs to be tested!!!
=> Force fsm to idle

cores/vata_460p3/src/vata_460p3_iface_fsm.vhd
Update tested on 2-asic test setup.
=> Possible triggering bug found.

scripts/env.bat, src/petalinux/apps/silayer-server/data_emitter.cpp, src/petalinux/apps/silayer-server/data_emitter.hpp, src/petalinux/apps/silayer-server/data_packet.cpp, src/petalinux/apps/silayer-server/data_packet.hpp
Note that partial data definitely arrives out of order!
Also fixed packet flags to actually flag missing data.
=> Now partial packets will get sent.

scripts/env.bat, src/petalinux/apps/silayer-server/data_emitter.cpp, src/petalinux/apps/silayer-server/data_emitter.hpp, src/petalinux/apps/silayer-server/data_packet.cpp, src/petalinux/apps/silayer-server/data_packet.hpp
Reverts ComPair/ComPair-tracker-FPGA#143
More thorough review process now enforced.
=> Revert "Now partial packets will get sent."

timing_diagram/.gitattributes, timing_diagram/README.txt, timing_diagram/Sean_WaveDrom.png, timing_diagram/Sean_WaveDrom.txt, timing_diagram/Syntax.txt, timing_diagram/VATA460.3_figure6.png, timing_diagram/VATA460.3_figure6.txt, timing_diagram/VATA460.3_figure7.png, timing_diagram/VATA460.3_figure7.txt, timing_diagram/VATA460.3_figure8.png, timing_diagram/VATA460.3_figure8.txt
Added the WaveDrom scripts and timing diagrams present in the VATA460.3  data sheet.
=> Added wavedrom timing diagrams

src/petalinux/apps/silayer-lib/include/cal_ctrl.hpp, src/petalinux/apps/silayer-lib/include/dac_ctrl.hpp, src/petalinux/apps/silayer-lib/include/vata_constants.hpp, src/petalinux/apps/silayer-lib/src/cal_ctrl.cpp, src/petalinux/apps/silayer-lib/src/dac_ctrl.cpp, src/petalinux/apps/silayer-server/silayer_server.cpp
It looks like the silayer server was not writing the calctrl settings.
Hopefully this fixes the problem.
=> Addressing issue 152.

src/petalinux/users/copy-scripts.sh, src/petalinux/users/sean/profile.d/sean-settings.sh
=> Adding some additional scripts.
